export const THEME = {
  COLORS: {
    BACKGROUND: "#000000",
    BACKGROUND_NAVBAR_HEADER: "#181616",
    BACKGROUND_CARD: "#181616",
    BACKGROUND_MODAL: "#181616",
    BACKGROUND_INPUT_MODAL: "#C4C4C4",
    BACKGROUND_DETAILS_TAB: "#000000",
    BACKGROUND_DETAILS_INFO: "#181616",
    SCREEN_MODAL: "rgba(0, 0, 0, 0.5)",
    WHITE: "#000000",
    YELLOW: "#FFD02C",

    TEXT: "#FFFFFF",
    SUB_TEXT: "#9A9A9A",
    POINTER: "#F22828",
    BUTTON_TEXT: "#FFFFFF",
    DETAILS_TEXT: "#FFFFFF",

    DIVIDER: "#D4D4D8",

    ACTIVE: "#FFFFFF",
    DESACTIVE: "#585858",
  },

  FONT_FAMILY: {
    REGULAR: "Inter_400Regular",
    SEMI_BOLD: "Inter_600SemiBold",
    BOLD: "Inter_700Bold",
    BLACK: "Inter_900Black",
  },

  FONT_SIZE: {
    SM: 14,
    MD: 16,
    LG: 20,
  },
};
export const THEME_ = {
  COLORS: {
    BACKGROUND: "#F6F6F5",
    BACKGROUND_NAVBAR_HEADER: "#FFFFFF",
    BACKGROUND_CARD: "#FFFFFF",
    BACKGROUND_MODAL: "#FFFFFF",
    BACKGROUND_INPUT_MODAL: "#F6F6F5",
    BACKGROUND_DETAILS_TAB: "#000000",
    BACKGROUND_DETAILS_INFO: "#FFFFFF",
    SCREEN_MODAL: "rgba(0, 0, 0, 0.5)",
    WHITE: "#FFFFFF",
    YELLOW: "#FFD02C",

    TEXT: "#000000",
    SUB_TEXT: "#9A9A9A",
    POINTER: "#F22828",
    BUTTON_TEXT: "#1976D2",
    DETAILS_TEXT: "#FFFFFF",

    DIVIDER: "#D4D4D8",

    ACTIVE: "#1976D2",
    DESACTIVE: "#C4C4C4",
  },

  FONT_FAMILY: {
    REGULAR: "Inter_400Regular",
    SEMI_BOLD: "Inter_600SemiBold",
    BOLD: "Inter_700Bold",
    BLACK: "Inter_900Black",
  },

  FONT_SIZE: {
    SM: 14,
    MD: 16,
    LG: 20,
  },
};
